export {default as Banner } from "./Banner"
export {default as HotSale } from "./HotSale"
export {default as Navbar } from "./Navbar"
export {default as Slide } from "./Slide"
export {default as PaymentMethods } from "./PaymentMethods"